name: lume_dating_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  card_swiper: ^2.0.4
  dio: ^5.3.2
  image_picker: ^1.0.4
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Lumé.png
    - assets/images/user1.jpg
    - assets/images/user2.jpg
    - assets/images/user3.jpg
    - assets/images/user4.jpg
    - assets/images/user5.jpg
    - assets/images/google_logo.png
    - assets/images/apple_logo.png
